#!/bin/bash

# Use this script to tail a specific cluster node log file.

usage() {
  echo "Usage: $0 node - Tail cluster node number, between 1-9" ; exit 1
}

[ $# -eq 0 ] && usage

node=$1
jarFilename=$(find target -name *allinone.jar)

tailNode() {
  node=$1
  port="255"$node
  tail -f /tmp/$(basename $PWD)-$node.log
}

if [[ $node =~ ^[1-9]$ ]] ; then
  tailNode $node
else
  echo "Cluster node number $node is invalid"
  usage
fi
